### ISSUE TITLE
bower bootstrap.js błędna ścieżka

### ISSUE THREAD

**Issue by konradperko** [PGS-dev/gulp-angular-sample-project#1]
Gdy załadowałem do projektu bootstrapa bowerem i podałem ścieżkę do pliku, gulp wyrzucił mi błąd: http://screencast.com/t/SAj3DYcX . W gulp-config/sources.js w linii 36:
paths.app + 'bower_components/_/{dist,min,release}/_.{js,css}'
musiałem dodac sciezke dist/js (taka jest w bowerowym boostrapie), czyli:
paths.app + 'bower_components/_/{dist,dist/js,min,release}/_.{js,css}'

**Comment by Frizi** [comment]
W takiej sytuacji wypada też dodać `dist/css` asekuracyjnie.

**Comment by Frizi** [comment]
fixed 7c5d158a
